Repository wilhelm-lab/oktoberfest, pull requests merged in 2023-07, with the labels that each got.

#89 Fix/check rawfile exists
  .cookietemple.yml
  .github/release-drafter.yml
  cookietemple.cfg
  docs/conf.py
  oktoberfest/__init__.py
  oktoberfest/re_score.py
  pyproject.toml
Labels: bug

#87 fragmentation_grpc column / support for PTM models
  oktoberfest/spectral_library.py
Labels: enhancement

#94 Fix/integration test
  Dockerfile
  ReadMe.md
  data/plasma/ReadMe.md
  data/plasma/config.json
  example_config.json
  oktoberfest/spectral_library.py
  oktoberfest/utils/config.py
  tests/integration_tests/test_re_score.py
Labels: bug, chore

#95 Feature/documentation
  README.rst
  ReadMe.md
  docs/API.rst
  docs/_key_contributors.rst
  docs/authors.rst
  docs/conf.py
  docs/contributors.md
  docs/index.rst
  docs/installation.rst
  docs/news.rst
  docs/readme.rst
  docs/reference.rst
  docs/requirements.txt
  docs/usage.rst
  noxfile.py
  oktoberfest/data/spectra.py
  oktoberfest/spectral_library.py
  requirements.txt
Labels: enhancement, chore

#96 Read input/output paths from config and restructure it
  Makefile
  MakefileShared
  README.rst
  ReadMe.md
  data/plasma/ReadMe.md
  data/plasma/config.json
  docs/usage.rst
  example_config.json
  oktoberfest/ce_calibration.py
  oktoberfest/re_score.py
  oktoberfest/run_oktoberfest.py
  oktoberfest/runner.py
  oktoberfest/spectral_library.py
  oktoberfest/utils/config.py
  tests/integration_tests/test_re_score.py
  tutorials/Oktoberfest Tutorial.ipynb
Labels: enhancement, chore
