Repository wilhelm-lab/oktoberfest, pull requests merged in 2023-10, with the labels that each got.

#108 Feature/api
  .cookietemple.yml
  .flake8
  .github/release-drafter.yml
  .gitignore
  .readthedocs.yml
  Dockerfile
  README.rst
  ReadMe.md
  cookietemple.cfg
  docs/API.rst
  docs/_static/custom_cookietemple.css
  docs/_templates/autosummary/base.rst
  docs/code_of_conduct.rst
  docs/conf.py
  docs/index.rst
  docs/installation.rst
  docs/news.rst
  docs/oktoberfest.data.rst
  docs/oktoberfest.rst
  docs/oktoberfest.utils.rst
  docs/readme.rst
  docs/reference.rst
  oktoberfest/__init__.py
  oktoberfest/__main__.py
  oktoberfest/calculate_features.py
  oktoberfest/ce_calibration.py
  oktoberfest/data/__init__.py
  oktoberfest/data/spectra.py
  oktoberfest/plotting/__init__.py
  oktoberfest/plotting/plotting.py
  oktoberfest/predict/__init__.py
  oktoberfest/predict/predict.py
  oktoberfest/preprocessing/__init__.py
  oktoberfest/preprocessing/preprocessing.py
  oktoberfest/py.typed
  oktoberfest/re_score.py
  oktoberfest/rescore/__init__.py
  oktoberfest/rescore/rescore.py
  oktoberfest/run_oktoberfest.py
  oktoberfest/runner.py
  oktoberfest/spectral_library.py
  oktoberfest/utils/__init__.py
  oktoberfest/utils/config.py
  oktoberfest/utils/multiprocessing_pool.py
  oktoberfest/utils/plotting.py
  poetry.lock
  pyproject.toml
  tests/unit_tests/data/mokapot/original.tab
  tests/unit_tests/data/predictions/library_input.csv
  tests/unit_tests/data/predictions/library_output.csv
  tests/unit_tests/test_job_pool.py
  tests/unit_tests/test_mokapot.py
  tests/unit_tests/test_predictions.py
  tests/unit_tests/test_utils.py
Labels: enhancement, chore

#138 Chore/documentation improvements
  README.rst
  ReadMe.md
  docs/API.rst
  docs/_static/img/Oktoberfest.svg
  docs/config.rst
  docs/contributors.md
  docs/index.rst
  docs/installation.rst
  docs/jobs.rst
  docs/quickstart.rst
  docs/readme.rst
  docs/reference.rst
  docs/requirements.txt
  example_config.json
  noxfile.py
  oktoberfest/__init__.py
  oktoberfest/preprocessing/preprocessing.py
  oktoberfest/utils/__init__.py
  oktoberfest/utils/example_configs.py
  poetry.lock
  pyproject.toml
  requirements.txt
  tutorials/Oktoberfest Tutorial.ipynb
Labels: chore

#137 Fix/filename not in msms
  oktoberfest/__init__.py
  oktoberfest/__main__.py
  oktoberfest/preprocessing/preprocessing.py
  oktoberfest/runner.py
Labels: bug

#150 Fix/fasta digest output
  oktoberfest/runner.py
  tests/unit_tests/configs/spectral_library_with_digest.json
  tests/unit_tests/data/test.fasta
  tests/unit_tests/test_runner.py
Labels: bug
