Repository wilhelm-lab/oktoberfest, pull requests merged in 2023-02, with the labels that each got.

#31 Added plotting
  .darglint
  .flake8
  .pre-commit-config.yaml
  ReadMe.md
  data/plasma/config.json
  example_config.json
  oktoberfest/calculate_features.py
  oktoberfest/ce_calibration.py
  oktoberfest/re_score.py
  oktoberfest/runner.py
  oktoberfest/utils/config.py
  oktoberfest/utils/plotting.py
  oktoberfest/utils/process_step.py
  poetry.lock
  pyproject.toml
Labels: chore

#33 support capital .RAW and lowercase .raw ext
  oktoberfest/re_score.py
Labels: enhancement

#30 Fix/docker build
  Makefile
  MakefileShared
  data/plasma/ReadMe.md
  oktoberfest/__main__.py
Labels: bug, chore

#35 Fix/docker build
  oktoberfest/ce_calibration.py
Labels: bug

#34 Vg/minor fixes
  ReadMe.md
  example_config.json
  oktoberfest/calculate_features.py
  oktoberfest/ce_calibration.py
  oktoberfest/certificates/Proteomicsdb-Prosit-v2.crt
  oktoberfest/re_score.py
  oktoberfest/runner.py
  oktoberfest/spectral_library.py
  oktoberfest/utils/config.py
  oktoberfest/utils/plotting.py
  tutorials/Oktoberfest Tutorial.ipynb
Labels: bug, chore

#37 Vg/minor fixes
  tutorials/Oktoberfest Tutorial.ipynb
Labels: bug
