Repository wilhelm-lab/oktoberfest, pull requests merged in 2023-06, with the labels that each got.

#72 Feature/plotting
  oktoberfest/ce_calibration.py
  oktoberfest/re_score.py
  oktoberfest/utils/plotting.py
  poetry.lock
  pyproject.toml
Labels: enhancement

#75 Feature/koina grpc
  data/plasma/Plamsa_03401_RD2_30min_Top10_86ms_RP13_R1.raw
  data/plasma/ReadMe.md
  data/plasma/config.json
  data/plasma/mqpar.xml
  data/plasma/msms.txt
  example_config.json
  oktoberfest/ce_calibration.py
  oktoberfest/certificates/Proteomicsdb-Prosit-v2.crt
  oktoberfest/re_score.py
  oktoberfest/runner.py
  oktoberfest/spectral_library.py
  oktoberfest/utils/plotting.py
  poetry.lock
  pyproject.toml
  tutorials/Oktoberfest Tutorial.ipynb
Labels: enhancement, performance

#70 Added mokapot as an alternative fdr_estimation_method for percolator
  ReadMe.md
  oktoberfest/re_score.py
  oktoberfest/runner.py
  oktoberfest/utils/config.py
  oktoberfest/utils/plotting.py
  poetry.lock
  pyproject.toml
  tests/integration_tests/test_re_score.py
Labels: enhancement, chore
